version: '2'

services:
  xcatmn:
    #the xCAT docker image name and tag, with format [xCAT docker image name]:[tag]
    image: schwarzwald/xcat-docker
    #Needed to run as systemd service. Otherwise will freeze upon startup.
    cap_add:
      - SYS_ADMIN
    #tty enable
    tty: true
    #stdin enable
    stdin_open: true
    #the /etc/hosts entry of container itself to be added into /etc/hosts inside container
    #the format is "[FQDN] [host name]: [IP address]"
    #FQDN is madatory. the domain name of FQDN will be set in site.domain
    extra_hosts: 
      - "xcatmn.clusters.com xcatmn:10.0.3.10"
    #the network objects the container will be connected to
    networks:
      #the service network, connecting to the hardware control point of the cluster
      svcnet:
        #the IP address of container in service network
        ipv4_address : 10.0.4.10
      #the management network, connecting to the compute nodes in the cluster
      mgtnet:
        #the IP address of container in management network
        ipv4_address : 10.0.3.10
       
    volumes:
      #the "/install" volume is used to keep user data in xCAT,
      #such as osimage resources
      - xcat-install:/install
      #the "/.dbbackup" volume is used to backup and restore xCAT DB tables
      #Dockerized xCAT will restore xCAT DB tables if specified
      #"dumpxCATdb -p /.dbbackup" should be run manually to save xCAT DB inside container
      - xcat-dbbackup:/.dbbackup
      #the "/var/log/xcat/" volume is used to keep xCAT logs
      - xcat-logs:/var/log/xcat
      #tftpboot generated files
      - xcat-tftpboot:/tftpboot

volumes:
  xcat-install:
  xcat-dbbackup:
  xcat-logs:
  xcat-tftpboot:

networks:
  mgtnet:
    driver: "macvlan"
    driver_opts:
      parent: enp2s0.03 
      com.docker.network.bridge.name: "mgtbr" 
      #com.docker.network.bridge.host_binding_ipv4: "10.5.107.1"
    ipam: 
      config: 
          #the subnet of the bridge network in CIDR format
          #should be exactly the same as the network configuration of network interface 
          #attached to the bridge
        - subnet: 10.0.3.0/24
          #the IP address of the bridge, should be exactly the same as the IP address of 
          #network interface attached to the bridge
          gateway: 10.0.3.1
          #aux_addresses:
          #   DefaultGatewayIPv4: 10.0.0.103
    
  #service network, attached to the network interface on
  #Docker host facing the bmc network
  svcnet:
    driver: "macvlan"
    driver_opts:
      parent: enp2s0.04
      com.docker.network.bridge.name: "svcbr" 
      #com.docker.network.bridge.host_binding_ipv4: "192.168.0.1"
    ipam: 
      config: 
          #the subnet of the bridge network in CIDR format
          #should be exactly the same as the network configuration of network interface 
          #attached to the bridge
        - subnet: 10.0.4.0/24
          #the IP address of the bridge, should be exactly the same as the IP address of 
          #network interface attached to the bridge
          gateway: 10.0.4.1
          #aux_addresses:
          #   DefaultGatewayIPv4: 10.5.107.1
